
# AttributeError: 'Function' object has no attribute 'fn' [in caffe] - 机器学习的小学生 - CSDN博客


2018年11月01日 09:20:30[机器学习的小学生](https://me.csdn.net/xuluhui123)阅读数：185



```python
n
```
```python
.
```
```python
global_pool_prob3
```
```python
=
```
```python
L
```
```python
.
```
```python
Sigmoid
```
```python
(
```
```python
n
```
```python
.
```
```python
global_pool_up3
```
```python
,
```
```python
name
```
```python
=
```
```python
'global_pool_prob3'
```
```python
,
```
```python
ntop
```
```python
=
```
```python
0
```
```python
,
```
```python
top
```
```python
=
```
```python
'global_pool_up3'
```
```python
)
```
```python
n
```
```python
.
```
```python
att_repmat3
```
```python
=
```
```python
L
```
```python
.
```
```python
Tile
```
```python
(
```
```python
n
```
```python
.
```
```python
global_pool_prob3
```
```python
,
```
```python
tile_param
```
```python
=
```
```python
{
```
```python
'axis'
```
```python
:
```
```python
1
```
```python
,
```
```python
'tiles'
```
```python
:
```
```python
256
```
```python
}
```
```python
)
```
报错产生的原因是，下一层使用的不是上一层top的名字，而是等式最左边的名字，修改为如下即可：
```python
n
```
```python
.
```
```python
global_pool_prob3
```
```python
=
```
```python
L
```
```python
.
```
```python
Sigmoid
```
```python
(
```
```python
n
```
```python
.
```
```python
global_pool_up3
```
```python
,
```
```python
name
```
```python
=
```
```python
'global_pool_prob3'
```
```python
,
```
```python
ntop
```
```python
=
```
```python
0
```
```python
,
```
```python
top
```
```python
=
```
```python
'global_pool_up3'
```
```python
)
```
```python
n
```
```python
.
```
```python
att_repmat3
```
```python
=
```
```python
L
```
```python
.
```
```python
Tile
```
```python
(
```
```python
n
```
```python
.
```
```python
global_pool_up3
```
```python
,
```
```python
tile_param
```
```python
=
```
```python
{
```
```python
'axis'
```
```python
:
```
```python
1
```
```python
,
```
```python
'tiles'
```
```python
:
```
```python
256
```
```python
}
```
```python
)
```

